// Bundles the engine into a single string the app can inline into the snippet
// people copy out. The result is committed, so `pnpm build` needs no pre-step —
// and a test recomputes the hash below and fails if the sources have moved on.
//
//   pnpm build:engine
//
// The bundle is an ES module with `three` left external: the snippet carries an
// import map pointing `three` and `three/addons/` at jsDelivr, so the engine is
// tens of KB and Three itself comes from a CDN the browser may already have.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "src", "engine", "dist", "engineSource.ts");

const result = await build({
  entryPoints: [path.join(ROOT, "src", "engine", "embed.ts")],
  bundle: true,
  minify: true,
  format: "esm",
  target: "es2020",
  legalComments: "none",
  external: ["three", "three/addons/*"],
  write: false,
  metafile: true,
});

let source = result.outputFiles[0].text.trim();

// The engine and the settings share one <script type="module"> scope, so the
// bundle's own `export { ... }` line is stripped: its two names (mount and
// coerceSpec) are simply in scope for the lines that follow.
const exportLine = source.match(/export\s*\{([^}]*)\}\s*;?\s*$/);
if (!exportLine) throw new Error("expected the bundle to end with an export line");
source = source.slice(0, exportLine.index).trim();
// Minification may have renamed the exports (`mount as a`); pin the public names.
const aliases = exportLine[1]
  .split(",")
  .map((part) => part.trim().split(/\s+as\s+/))
  .filter(([local, name]) => name && local !== name);
if (aliases.length) source += `\nconst ${aliases.map(([local, name]) => `${name}=${local}`).join(",")};`;

// Exactly what esbuild pulled in, so the hash covers the real dependency set
// rather than a hand-kept list that drifts.
const inputs = Object.keys(result.metafile.inputs)
  .map((file) => path.relative(ROOT, path.resolve(ROOT, file)))
  .sort();

const hash = createHash("sha256");
for (const input of inputs) {
  hash.update(input);
  hash.update(await readFile(path.join(ROOT, input)));
}

const threeVersion = JSON.parse(await readFile(path.join(ROOT, "node_modules", "three", "package.json"), "utf8")).version;

const file = `// GENERATED by scripts/build-engine.mjs — do not edit.
//
// The engine, bundled and minified, as a string. This is what gets inlined into
// the block people copy out, and it is the *same code the preview runs* — which
// is the whole architecture in one file: what you see is what you copy, by
// construction rather than by discipline.
//
// Committed on purpose, so a production build has no pre-step. engineSource.test.ts
// recomputes the hash from the sources below and fails if they have moved on.
// Run \`pnpm build:engine\` when they have.

/** The Three.js the bundle was built against; the snippet's import map pins the CDN to it. */
export const THREE_VERSION = ${JSON.stringify(threeVersion)};

/** Sources the bundle was built from, as esbuild resolved them. */
export const ENGINE_INPUTS = ${JSON.stringify(inputs, null, 2)};

/** sha256 over those sources, in this order, name then contents. */
export const ENGINE_HASH = ${JSON.stringify(`sha256:${hash.digest("hex")}`)};

export const ENGINE_SOURCE = ${JSON.stringify(source)};
`;

await writeFile(OUT, file);

const bytes = Buffer.byteLength(source, "utf8");
process.stdout.write(`${path.relative(ROOT, OUT)} — ${(bytes / 1024).toFixed(1)}KB minified from ${inputs.length} files\n`);
